### ISSUE TITLE
Improve state and props api with getters and setters

### ISSUE THREAD

**Issue by DominikGuzei** [meteor-space/template-controller#10]
We should investigate in `getters` and `setters` as this could improve the current api significantly.
Instead of `this.state.counter(newValue)` you could just assign it `this.state.counter = newValue` and it would update through the setter function (in the background). Same with getter of course, this would make it transparent. Not sure if Blaze supports this though, have to test.

**Comment by comerc** [comment]
https://github.com/meteor-space/template-controller/issues/18

**Comment by DominikGuzei** [comment]
We will have to use the ES5 compatible [getters / setters](http://javascriptplayground.com/blog/2013/12/es5-getters-setters/) for this feature

**Comment by comerc** [comment]
Yes! Current state syntax look terribly.

``` coffee
  if @state.nodeId()
    Nodes.update @state.nodeId(), $set: data
  else
    @state.nodeId(Nodes.insert data)
```

I want to live in perfect world :)

``` coffee
  if @state.nodeId
    Nodes.update @state.nodeId, $set: data
  else
    @state.nodeId = Nodes.insert data
```
