### ISSUE TITLE
Rename ['onCreated', 'onRendered', 'onDestroyed'] to ['created', 'rendered', 'destroyed']

### ISSUE THREAD

**Issue by comerc** [meteor-space/template-controller#16]
This will eliminate the confusion.

for example:

``` javascript
Template.hello.rendered = TemplateTwoWayBinding.rendered;
// or
// Template.hello.onRendered(function() {
//   TemplateTwoWayBinding.rendered.call(this);
// });
```

but:

``` javascript
TemplateController('hello', {
  onRendered: TemplateTwoWayBinding.rendered,
  // or
  // onRendered: function() {
  //   TemplateTwoWayBinding.rendered.call(this);
  // },
  state: {
    exampleVariable1: 'test'
  }
});
```

**Comment by DominikGuzei** [comment]
@comerc we would like to keep this api as close to the [official Blaze docs](http://docs.meteor.com/#/full/template_onRendered) as possible. I think your proposed change would actually cause more confusion 😉

**Comment by comerc** [comment]
Sorry, we can use both variants:

``` javascript
TemplateController('hello', {
  onRendered: function() {
  }
});
```

``` javascript
TemplateController('hello', {
  onRendered() {
  }
});
```

**Comment by DominikGuzei** [comment]
Hey @comerc can you elaborate, i don't understand what you mean with both variants – in your example the only difference is the usage of the ES6 function declaration shortcut.

**Comment by comerc** [comment]
[.rendered is deprecated](http://stackoverflow.com/questions/29809702/meteor-js-templates-rendered-vs-onrendered)

**Comment by DominikGuzei** [comment]
Yes i know, it was long time ago 😉  that's why we will keep using `onRendered` etc. which is also better because it allows multiple handlers to be added instead of a single one.

**Comment by comerc** [comment]
But we can have alias. For compatibled interface. May be.
