### ISSUE TITLE
How to add new state after init TemplateController?

### ISSUE THREAD

**Issue by comerc** [meteor-space/template-controller#17]
for example:

``` coffee
TemplateController 'demo',
  state: {}
  onCreated: ->
    @modelMap =
      'head': 'fieldHead'
      'body': 'fieldBody'
    for variable of @modelMap
      @state[variable] = generateReactiveAccessor()
```

But I does not have access to `generateReactiveAccessor()`

PS workaroind for me - [ReaciveField](https://github.com/peerlibrary/meteor-reactive-field) :)

**Comment by DominikGuzei** [comment]
Thanks for the reference to [ReactiveField](https://github.com/peerlibrary/meteor-reactive-field), looks great and i think we can introduce that. I will also add a section to the docs about generating reactive fields on the fly like in your example.

**Comment by DominikGuzei** [comment]
@comerc just changed my mind, `ReactiveField` will not be compatible with `getters` and `setters` syntax (see #10), so we will just roll our own here and i will expose a helper for the templates so you can add new state vars dynamically. Sounds good?

**Comment by comerc** [comment]
Very good!

**Comment by comerc** [comment]
Thanks!

**Comment by comerc** [comment]
My [demo](https://github.com/comerc/meteor-template-controller-demo) updated too.

**Comment by DominikGuzei** [comment]
great, thanks @comerc
