### ISSUE TITLE
Excessive nesting for declaring events in the code

### ISSUE THREAD

**Issue by comerc** [meteor-space/template-controller#19]
How about [this feature](https://github.com/ManuelDeLeon/viewmodel/issues/240)? It is important in my coffee code.

**Comment by DominikGuzei** [comment]
What is the benefit of this compared to using the `events` property?
Please show me a proper use-case

**Comment by comerc** [comment]
Two spaces VS one! It is also best practiсes of Blaze templates.

I could not convince @ManuelDeLeon also. I want to see more opportunities, but did not abandon the usual code style. I do not need a blunt Swiss knife. :)

**Comment by DominikGuzei** [comment]
IMO this was one of the main reasons why we created this package in the first place.
We wanted to remove the boilerplate of having to repeat `Template.my_template` all over the place 😉 
Sorry, more opportunities also means more complicated explanations and less opinionated code (forcing best practice), which is the ultimate goal of this package.

**Comment by comerc** [comment]
OK! One more package for TemplateController by @comerc :)

**Comment by comerc** [comment]
Please export `bindToTemplateInstance()`

**Comment by comerc** [comment]
[You wrote](https://crater.io/posts/PWe2DGaKqHRKau3zL/templatecontroller-syntactic-sugar-for-blaze-templating-best):

> My only "problem" with these existing packages is that they introduce new concepts on top of the standard Blaze api.

It is my problem too. I believed you. :)

**Comment by comerc** [comment]
May be, not tested yet https://github.com/andrejsm/meteor-template-destruct

**Comment by DominikGuzei** [comment]
@comerc im not sure what your problem here really is, Javascript / Coffee is pretty versatile, so you can just write the template code like this:

``` coffeescript
my_template = {}
my_template.events =
  'click .something': -> …
  'click .other': -> …
my_template.onCreated = -> …
 # etc … and at the end of the file
TemplateController 'my_template', my_template
```

Of course this will be compatible with all features, because you're just passing a config object to `TemplateController`. There is nothing special going on 😉

**Comment by comerc** [comment]
Good idea, thanks!

**Comment by comerc** [comment]
But I want Singleton.

**Comment by comerc** [comment]
[Source](https://github.com/dalgard/meteor-viewmodel#usage):

> When a viewmodel is created on a template – either implicitly or explicitly – existing Blaze helpers on the template become properties of the viewmodel. The helpers preserve their normal context and arguments when called.

``` javascript
Template.example.viewmodel({
  myValue: "Hello world"
});

Template.example.onRendered(function () {
  console.log(this.viewmodel.myValue());  // "Hello world"
});

Template.example.events({
  "click button"(event, template_instance) {
    console.log(template_instance.viewmodel.myValue());  // "Hello world"
  }
});

// Additional helpers shouldn't be needed in practice, since all viewmodel
// properties are also registered as Blaze helpers
Template.example.helpers({
  myHelper() {
    return Template.instance().viewmodel.myValue();  // "Hello world"
  }
});

// If no name is specified for a viewmodel, it is named after its view
Template.other.helpers({
  otherHelper() {
    return ViewModel.findOne("Template.example").myValue();  // "Hello world"
  }
});
```

I love this style to migration to new world.

**Comment by DominikGuzei** [comment]
This works exactly the same with `TemplateController`, there is nothing special going on – it's just syntactic sugar for doing it yourself 😉  you can also just declare any additional helpers, events and everything else like normal. In fact, we are doing it "like normal" compared to viewmodel package that has some woodoo magical template language going on behind the scenes.

``` javascript
TemplateController('example', {
  state: {
   myValue: "Hello world"
  }
});

Template.example.onRendered(function () {
  console.log(this.state.myValue);  // "Hello world"
});

Template.example.events({
  "click button"(event, template_instance) {
    console.log(template_instance.state.myValue);  // "Hello world"
  }
});

Template.example.helpers({
  myHelper() {
    return Template.instance().state.myValue;  // "Hello world"
  }
});
```

Remember: this package does nothing new, it exclusively uses the existing Blaze api with no addition at all … except enforcing best practices.

**Comment by comerc** [comment]
But I dont use:

``` javascript
Template.example.helpers({
  myHelper() {
    return this.state.myValue;  // "Hello world"
  }
});
```

OK. It is true. `Template.example.helpers` - it is template helpers, but we have one more feature - TemplateController helpers with other context and other rules of declaration.

**Comment by comerc** [comment]
i.e.

``` javascript
TemplateController.example.helpers({
  myHelper() {
    return this.state.myValue;  // "Hello world"
  }
});
```

:)

**Comment by DominikGuzei** [comment]
@comerc sorry i don't see the big benefit, not gonna happen 😉

**Comment by comerc** [comment]
I know how to implement this feature :)

**Comment by DominikGuzei** [comment]
you're free to setup a pull request but i would really like to focus on real features instead. Im not a big fan of thousand different ways to declare helpers etc. this adds just confusion and does not bring much value.

**Comment by comerc** [comment]
It is important feature for me! :) For one more example. I need to store helpers and events of one Template instance in two separated files.

**Comment by DominikGuzei** [comment]
@comerc if you can give a full use-case scenario that makes sense we can continue discussing this. I never had the need (or want) to split up my template code into multiple files and don't think it's best practice.

**Comment by comerc** [comment]
I don't know all scenarios, of course. I just listed above are some reasons. But MDG give to us this feature and it would be extremely not prudent to remove this feature.

**Comment by comerc** [comment]
Implemetation

``` javascript
  TemplateController.helpers = function (templateName, helperMap) {
    let template = Template[templateName];
    if (!template) {
      throw templateNotFoundError(templateName);
    }
    template.helpers(TemplateController.bindAllToTemplateInstance(helperMap));
  }

  TemplateController.events = function (templateName, eventMap) {
    let template = Template[templateName];
    if (!template) {
      throw templateNotFoundError(templateName);
    }
    template.events(TemplateController.bindAllToTemplateInstance(eventMap));
  }
```

Usage

``` coffee
TemplateController.events 'hello',
  'click button': ->
    @state.counter++;
```

**Comment by comerc** [comment]
V2 

``` javascript
  Template.prototype.controllerEvents = function (eventMap) {
    this.events(TemplateController.bindAllToTemplateInstance(eventMap));
  }
```

Usage

``` coffee
Template.hello.controllerEvents 
  'click button': ->
    @state.counter++
```

**Comment by comerc** [comment]
But I want

``` coffee
TemplateController.hello.events
  'click button': ->
    @state.counter++
```
