### ISSUE TITLE
TemplateController vs Template2?

### ISSUE THREAD

**Issue by thearabbit** [meteor-space/template-controller#35]
Now I found the `Template2`.
What difference `TemplateController vs Template2`

**Comment by comerc** [comment]
TemplateController preaches simple way for incapsulate state and props (with validation). It is cool!

Template2 inherits these ideas. Plus more features.

Template2 lives inside Blaze.TemplateInstance - minimum changes for migration your great project to perfect world.

Template2 has Helpers and Events declaration by old style, but with context by Template.instance() (as TemplateController).

``` javascript
// old style:
Template.hello.helpers({
  test: function() {
    // this - Template.currentData()
  }
});
// plus more:
Template.hello.helpersByInstance({
  test: function() {
    // this - Template.instance() 
  }
});
// and as TemplateController:
Template2('hello', {
  helpers: {
    test: function() {
      // this - Template.instance() 
    }
  }
});
```

Template2 includes basic features [to implement MVVM](https://github.com/comerc/meteor-template2#basic-usage): view input-data from Model, validation input-data by Model Schema and store input-data to Model via Two-Way Binding w/o mapping of variables for intermediate operations.

Two-Way Binding features may be used w/o Model ([demo](https://github.com/comerc/meteor-mvvm-mdl-demo)).

Also from Template2 was excluded some features of TemplateController: [one](https://github.com/meteor-space/template-controller#private--myproperty--mymethod-), [two](https://github.com/meteor-space/template-controller#thistriggereventeventname-data).

**Comment by thearabbit** [comment]
Thanks for your explain.
