### ISSUE TITLE
Passing a full mongo document as props with SimpleSchema

### ISSUE THREAD

**Issue by mcoenca** [meteor-space/template-controller#36]
Maybe noobie mistake, but How can you pass a full mongodb document through props ? 

Meteor 1.2.2-faster-rebuilds.0
aldeed:simple-schema@1.5.3
space:template-controller@0.3.0
I've tried 

`
Template('Bridge',
props: new SimpleSchema({
bridge: {
      type: Object,
      blackbox: true,
    },
}),
...
`

But it tells me 'bridge must be an Object'... Don't know how SimpleSchema is testing its type, but it must be checking against the Document class name. Do you how to specify this type in my Schema (Maybe that's more a question for SimpleSchema than here ;p ) ? I've also tried Passing my whole collection schema Bridges.simpleSchema() to type, without success.

For now I am using a ugly object extension in my helper to be able to pass it to props with Object + blackbox
`each bridge in bridges
    +Bridge(bridge=bridge)
`

`bridges() {return Bridges.find({}).map(bri=>_.extend({},bri});}`

Thanks for your time, best !

**Comment by DominikGuzei** [comment]
Hey @mcoenca, yeah we also stumbled over that problem and honestly i'm not sure if we found a better solution there! But as you said this is a question about `SimpleSchema` – i see there is already some discussion around this topic: https://github.com/aldeed/meteor-simple-schema/issues/545

**Comment by mcoenca** [comment]
Ok great thanks ;0
