### ISSUE TITLE
triggerEvent is incompatible with content starting with a spacebar

### ISSUE THREAD

**Issue by Craphtex** [meteor-space/template-controller#6]
The triggerEvent uses firstNode when triggering its event. However if the template content starts with a spacebar then the firstNode will be a text node, causing the event to not trigger at all.

Here's two examples where any event triggered using triggerEvent will dissapear into the void.
_Ex 1:_
_Parent:_

``` HTML
{{> example1}}
```

_Child:_

``` javascript
<template name="example1">
  {{# if true}}
    <p>A</p>
  {{/if}}
  <p>B</p>
</template>
```

_Ex 2:_
_Parent:_

``` HTML
{{# example2}}
  <p>A</p>
{{/example2}}
```

_Child:_

``` javascript
<template name="example2">
  {{> Template.contentBlock}}
  <p>B</p>
</template>
```

The TemplateController never claims to support these scenarios, but as a similar implementaion is very likely to be used when using the TemplateController at least a note in the documentation might be a good idea.

**Comment by DominikGuzei** [comment]
Good catch, looking into the issue now!
